"""init

Revision ID: d33282622135
Revises: 
Create Date: 2026-06-21 20:58:10.740390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd33282622135'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('node_id', sa.BigInteger(), nullable=True),
    sa.Column('artifact_type', sa.String(length=50), nullable=False, comment='knowledge_tree/content/quiz'),
    sa.Column('artifact_id', sa.BigInteger(), nullable=True, comment='对应的内容/题目 ID'),
    sa.Column('verdict', sa.String(length=30), nullable=False, comment='passed/passed_with_notes/not_passed'),
    sa.Column('checks_json', sa.JSON(), nullable=False, comment='检查项详情'),
    sa.Column('failed_hard_count', sa.Integer(), nullable=False),
    sa.Column('failed_soft_count', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('final_verdict', sa.String(length=30), nullable=False, comment='最终裁决'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_records_node_id'), 'audit_records', ['node_id'], unique=False)
    op.create_index(op.f('ix_audit_records_project_id'), 'audit_records', ['project_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=False, comment='微信 openid'),
    sa.Column('nickname', sa.String(length=100), nullable=False, comment='昵称'),
    sa.Column('avatar', sa.String(length=500), nullable=False, comment='头像 URL'),
    sa.Column('profile_json', sa.JSON(), nullable=False, comment='学习偏好、速度、薄弱点等'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False, comment='科目名称'),
    sa.Column('goal_description', sa.Text(), nullable=False, comment='学习目标'),
    sa.Column('goal_type', sa.String(length=50), nullable=False, comment='exam/skill/interest'),
    sa.Column('deadline', sa.Date(), nullable=True, comment='截止日期'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='active/completed/paused'),
    sa.Column('tree_version', sa.Integer(), nullable=False, comment='知识图谱版本'),
    sa.Column('tree_total_nodes', sa.Integer(), nullable=False, comment='节点总数'),
    sa.Column('tree_total_hours', sa.Numeric(precision=5, scale=1), nullable=False, comment='预计总学时'),
    sa.Column('plan_strategy', sa.JSON(), nullable=False, comment='学习策略配置'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('session_key', sa.String(length=100), nullable=False, comment='会话标识'),
    sa.Column('messages', sa.JSON(), nullable=False, comment='对话消息列表'),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_project_id'), 'conversations', ['project_id'], unique=False)
    op.create_index(op.f('ix_conversations_session_key'), 'conversations', ['session_key'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('nodes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('node_key', sa.String(length=100), nullable=False, comment='节点标识（如 mod-01-02）'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='节点标题'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父节点 ID'),
    sa.Column('level', sa.Integer(), nullable=False, comment='层级深度'),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False, comment='预计学习时间（分钟）'),
    sa.Column('prerequisites', sa.JSON(), nullable=False, comment='前置节点 ID 列表'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending/in_progress/completed'),
    sa.Column('mastery_level', sa.Numeric(precision=3, scale=2), nullable=False, comment='掌握度 0.00~1.00'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_project_id'), 'nodes', ['project_id'], unique=False)
    op.create_table('study_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('study_date', sa.Date(), nullable=False, comment='学习日期'),
    sa.Column('minutes_spent', sa.Integer(), nullable=False, comment='学习时长（分钟）'),
    sa.Column('nodes_completed', sa.Integer(), nullable=False, comment='完成节点数'),
    sa.Column('quizzes_taken', sa.Integer(), nullable=False, comment='完成测验数'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'study_date', name='uq_user_study_date')
    )
    op.create_index(op.f('ix_study_logs_project_id'), 'study_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_study_logs_user_id'), 'study_logs', ['user_id'], unique=False)
    op.create_table('contents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False, comment='lesson/summary/exercise/example'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='教材标题'),
    sa.Column('content_json', sa.JSON(), nullable=False, comment='完整内容'),
    sa.Column('word_count', sa.Integer(), nullable=False, comment='字数'),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False, comment='easy/normal/hard'),
    sa.Column('audit_status', sa.String(length=30), nullable=False, comment='pending/passed/not_passed'),
    sa.Column('audit_retry_count', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='发布（推送）时间'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contents_node_id'), 'contents', ['node_id'], unique=False)
    op.create_index(op.f('ix_contents_user_id'), 'contents', ['user_id'], unique=False)
    op.create_table('mastery_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('node_id', sa.BigInteger(), nullable=False),
    sa.Column('mastery_level', sa.Numeric(precision=3, scale=2), nullable=False, comment='掌握度 0.00~1.00'),
    sa.Column('assessment_type', sa.String(length=30), nullable=False, comment='quiz/review/self_report'),
    sa.Column('assessed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mastery_history_node_id'), 'mastery_history', ['node_id'], unique=False)
    op.create_index(op.f('ix_mastery_history_user_id'), 'mastery_history', ['user_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('quiz_type', sa.String(length=50), nullable=False, comment='pre_test/post_test/review/practice'),
    sa.Column('questions', sa.JSON(), nullable=False, comment='题目列表'),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('answers_json', sa.JSON(), nullable=False, comment='用户答案详情'),
    sa.Column('mastery_before', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('mastery_after', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_node_id'), 'quizzes', ['node_id'], unique=False)
    op.create_index(op.f('ix_quizzes_user_id'), 'quizzes', ['user_id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('node_id', sa.BigInteger(), nullable=False),
    sa.Column('planned_start', sa.Date(), nullable=False, comment='计划开始日期'),
    sa.Column('planned_end', sa.Date(), nullable=False, comment='计划结束日期'),
    sa.Column('actual_start', sa.DateTime(), nullable=True),
    sa.Column('actual_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='planned/in_progress/completed/delayed/skipped'),
    sa.Column('progress_percent', sa.Integer(), nullable=False, comment='进度百分比'),
    sa.Column('adjusted_at', sa.DateTime(), nullable=True),
    sa.Column('adjust_reason', sa.Text(), nullable=False, comment='调整原因'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_node_id'), 'schedules', ['node_id'], unique=False)
    op.create_index(op.f('ix_schedules_project_id'), 'schedules', ['project_id'], unique=False)
    op.create_table('push_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False, comment='wechat/in_app'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='sent/delivered/read/completed'),
    sa.Column('pushed_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True, comment='1-5 评分'),
    sa.Column('feedback', sa.Text(), nullable=False, comment='文字反馈'),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_records_content_id'), 'push_records', ['content_id'], unique=False)
    op.create_index(op.f('ix_push_records_user_id'), 'push_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_push_records_user_id'), table_name='push_records')
    op.drop_index(op.f('ix_push_records_content_id'), table_name='push_records')
    op.drop_table('push_records')
    op.drop_index(op.f('ix_schedules_project_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_node_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_quizzes_user_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_node_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_mastery_history_user_id'), table_name='mastery_history')
    op.drop_index(op.f('ix_mastery_history_node_id'), table_name='mastery_history')
    op.drop_table('mastery_history')
    op.drop_index(op.f('ix_contents_user_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_node_id'), table_name='contents')
    op.drop_table('contents')
    op.drop_index(op.f('ix_study_logs_user_id'), table_name='study_logs')
    op.drop_index(op.f('ix_study_logs_project_id'), table_name='study_logs')
    op.drop_table('study_logs')
    op.drop_index(op.f('ix_nodes_project_id'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_session_key'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_project_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_audit_records_project_id'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_node_id'), table_name='audit_records')
    op.drop_table('audit_records')
    # ### end Alembic commands ###
